version: "3"

services:
  mongodb:
    image: mongo:4.0.2
    expose:
      - 27017
    networks:
      - todo

  node:
    build:
      context: server
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todos
      - PORT=8080
    networks:
      - todo
    expose:
      - 8080
    ports:
      - 8080:8080 # page

  client:
    build:
      context: client
    depends_on:
      - node
    networks:
      - todo
    environment:
      - PORT=8081 # page
      - ENDPOINT=http://todo.liaojungang.com/api # 后端接口地址
    ports:
      - 8081:8081 # page
      # - 8888:8888 # webpack bundle analyzer

networks:

  todo:
    driver: bridge
