version: "3"

services:
  node:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - D:/code/_wy-hw/server:/server
      - /server/node_modules

  client:
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - D:/code/_wy-hw/client:/client
      - /client/node_modules
