version: "3"

services:
  node:
    build:
      args:
        - NODE_ENV=development
    ports:
      - 8080:8080 # node server running port
    environment:
      - PORT=8080
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - D:/code/tmp_dazuoye/server:/server
      - /server/node_modules

  client:
    ports:
      - 8081:8081 # webpack-dev-server
      - 8888:8888 # webpack bundle analyzer
    environment:
      - PORT=8081
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - D:/code/tmp_dazuoye/client:/client
      - /client/node_modules