version: "3"

services:
  node:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run prod

  client:
    command: npm run prod
    environment:
      - NODE_ENV=production
